version: '3'
services:
  magic:
    image: mageai/mageai:fifa
    container_name: ${PROJECT_NAME}-mage
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - /home/lorenz-gcp/batch-processing-fifa-dataset-on-gcp/mage/kaggle.json:/root/.kaggle/kaggle.json
      #- ~/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
    restart: on-failure:5